FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /mlflow

COPY requirements/mlflow.txt \
    /mlflow/requirements/mlflow.txt

RUN python -m pip install \
        --upgrade pip \
    && python -m pip install \
        -r /mlflow/requirements/mlflow.txt

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
